<?xml version="1.0"?>
<package format="3">
  <name>tank_bringup</name>
  <version>0.1.0</version>
  <description>tank-battle 启动包:launch 文件、battlefield.world、参数 YAML</description>
  <maintainer email="jokerxiao1218-cell@users.noreply.github.com">jokerxiao1218-cell</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>gazebo_ros</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>tank_description</exec_depend>
  <exec_depend>tank_nodes</exec_depend>
  <exec_depend>tank_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
